import { createHash, randomUUID } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { Redis } from "ioredis";
import { describe, expect, it, vi } from "vitest";
import { createCodexAdapters, type CodexParticipant } from "./qualification-codex.js";
import { createGenericAdapters } from "./qualification-generic.js";
import { startOwnedRedis, type OwnedRedis } from "./owned-redis.js";
import { collectPeerDiscovery } from "./qualification-discovery.js";
import { extractNativeTraces, extractGenericTraces } from "./qualification-evidence.js";
import { assertSetupTurnCompleted } from "./qualification-idle-task.js";
import { collectReadableDelivery } from "./qualification-readable.js";
import { sanitizeEvidence } from "./public-evidence.js";
import type { GenericParticipant, RawEvidenceRef } from "./qualification-types.js";
import { CODEX_BIN } from "./local-tools.js";

const gate = process.env.GPTQUEUE_QUALIFICATION_READABLE;
const enabled = gate === "ping" || gate === "status";
const messageType: "ping" | "status" = gate === "ping" ? "ping" : "status";
const repo = resolve(import.meta.dirname, "../..");
const root = join(repo, ".gptqueue/repair-qualification/20260912/qualification-readable-native");
vi.setConfig({ testTimeout: 480_000, hookTimeout: 60_000 });
type Json = Record<string, unknown>;
const obj = (x: unknown): Json | undefined => x && typeof x === "object" && !Array.isArray(x) ? x as Json : undefined;
const hash = (x: Uint8Array) => createHash("sha256").update(x).digest("hex");
const wait = (ms: number) => new Promise<void>(r => setTimeout(r, ms));
const ids = (h: unknown) => (Array.isArray(obj(h)?.turns) ? obj(h)!.turns as unknown[] : []).map(t => String(obj(t)?.id));
const ref = (path: string, bytes: Uint8Array, sourceRevision: string, oracleRevision: string): RawEvidenceRef => ({ path, sha256: hash(bytes), sourceRevision, oracleRevision });
const save = async (path: string, value: unknown) => { const bytes = Buffer.from(`${JSON.stringify(value)}\n`); await writeFile(path, bytes, { mode: 0o600 }); return { path, value: JSON.parse(bytes.toString()), bytes, sha256: hash(bytes) }; };
const sourceHashes = async (): Promise<Json> => {
  const trees = await Promise.all(["src", "dist", "tests/acceptance"].map(async d => (await readdir(join(repo, d), { recursive: true })).filter(p => /\.(?:ts|js|json)$/u.test(p)).map(p => `${d}/${p}`)));
  const labels = [...new Set(["package.json", "package-lock.json", "bin/gptqueue-session", "dist/mcp-server/index.js", ...trees.flat()])].sort();
  const files = Object.fromEntries(labels.map(p => [p, join(repo, p)])); files.node_executable = process.execPath; files.codex_executable = process.env.CODEX_BIN ?? CODEX_BIN; files.codex_native_executable = CODEX_BIN;
  return Object.fromEntries(await Promise.all(Object.entries(files).map(async ([k, p]) => [k, hash(await readFile(p))])));
};
const waitIdle = async (m: CodexParticipant, signal: AbortSignal): Promise<Json> => { const end = Date.now() + 30_000; while (Date.now() < end) { const s = await m.status(signal); if (s.kind === "idle" && s.runtimeId === m.identity.hostRuntimeId) return s as Json; if (s.kind === "terminated" || s.kind === "unknown") throw new Error("native model unavailable"); await wait(250); } throw new Error("native model did not become idle"); };
const turn = (h: unknown, id: string): Json | undefined => Array.isArray(obj(h)?.turns) ? (obj(h)!.turns as unknown[]).map(obj).find(t => t?.id === id) : undefined;

describe("native readable delivery qualification", () => {
  it("requires the exact readable gate", () => expect(gate === undefined || gate === "ping" || gate === "status").toBe(true));
  it.skipIf(!enabled)("proves prompted native readable delivery", async () => {
    const runId = randomUUID(), artifactDir = join(root, runId), phasesDir = join(artifactDir, "phases"); await mkdir(phasesDir, { recursive: true, mode: 0o700 });
    const receipt: Json = { schema_version: 1, run_id: runId, row_id: `codex-appserver:automatic:readable-${gate}`, route: "codex-appserver", model: "gpt-5.6-luna", gate: `GPTQUEUE_QUALIFICATION_READABLE=${gate}`, readability_mode: "explicit_controller_prompt", automatic_activation_claim: false, database: 15, runner_pid: process.pid, executable_paths: { node: process.execPath, codex: process.env.CODEX_BIN ?? CODEX_BIN, codex_native: CODEX_BIN }, phase: "running", passed: false, phases: [] };
    const persist = async (label: string, value: unknown) => { const phase = { label, at: new Date().toISOString(), value: sanitizeEvidence(value, { parseEmbeddedJson: true, redactSessionObjectIds: true }) }; const phaseList = receipt.phases as Json[]; phaseList.push(phase); await writeFile(join(phasesDir, `${String(phaseList.length).padStart(4, "0")}-${label}.json`), `${JSON.stringify(phase)}\n`, { mode: 0o600 }); await writeFile(join(artifactDir, "receipt.json"), `${JSON.stringify(sanitizeEvidence(receipt))}\n`, { mode: 0o600 }); };
    let redis: OwnedRedis | undefined, observer: Redis | undefined, workspace: string | undefined, model: CodexParticipant | undefined, peer: GenericParticipant | undefined; let codex: ReturnType<typeof createCodexAdapters> | undefined, generic: ReturnType<typeof createGenericAdapters> | undefined; let failure: unknown;
    const cleanup: Json[] = [];
    try {
      receipt.started_at = new Date().toISOString(); receipt.source_hashes_before = await sourceHashes(); await persist("started", { started_at: receipt.started_at, runner_pid: receipt.runner_pid, executable_paths: receipt.executable_paths, source_hashes_before: receipt.source_hashes_before });
      const sourceRevision = hash(Buffer.from(JSON.stringify(receipt.source_hashes_before))), oracleRevision = hash(await readFile(join(repo, "tests/acceptance/qualification-readable.ts"))); const signal = AbortSignal.timeout(420_000);
      redis = await startOwnedRedis(); observer = new Redis(redis.url); workspace = await mkdtemp(join(tmpdir(), "gptqueue-readable-native-")); receipt.redis = { port: Number(new URL(redis.url).port), database: 15, owned_process: true };
      const codexExecutable = process.env.CODEX_BIN ?? CODEX_BIN; codex = createCodexAdapters({ workspaceRoot: workspace, codexBin: codexExecutable, model: "gpt-5.6-luna" }); generic = createGenericAdapters({ repo }); const nativeAdapter = codex.adapters.find(x => x.spec.id === "codex-appserver"), genericAdapter = generic.adapters.find(x => x.spec.id === "generic-stdio"); if (!nativeAdapter || !genericAdapter) throw new Error("required adapters unavailable"); if ((await nativeAdapter.preflight(signal)).kind !== "available" || (await genericAdapter.preflight(signal)).kind !== "available") throw new Error("required adapter unavailable");
      peer = await genericAdapter.launch({ role: "sender", pairId: runId, nonce: `peer-${runId}`, redisUrl: redis.url }, signal) as GenericParticipant; model = await nativeAdapter.launch({ role: "receiver", pairId: runId, nonce: `model-${runId}`, redisUrl: redis.url }, signal) as CodexParticipant; receipt.identities = { model: model.identity, peer: peer.identity }; await persist("launched", receipt.identities);
      const controllerEvents: Json[] = []; const setupPrompt = "Use only gptqueue-shared. Call get_runtime_status and list_agents, then reply READY and end this turn."; controllerEvents.push({ kind: "controller_prompt", at: Date.now(), prompt: setupPrompt }); await peer.call("list_agents", {}, signal); const setup = await model.prompt(setupPrompt, signal); const baseline = await model.history(signal), peerBaseline = await peer.history(signal); assertSetupTurnCompleted(baseline, setup); const baselineFile = await save(join(artifactDir, "baseline-model-history.json"), sanitizeEvidence(baseline)); const peerFile = await save(join(artifactDir, "baseline-peer-history.json"), sanitizeEvidence(peerBaseline)); const native = extractNativeTraces(baselineFile.value, model.identity, ref(baselineFile.path, baselineFile.bytes, sourceRevision, oracleRevision)); const genericTraces = extractGenericTraces(peerFile.value, peer.identity, ref(peerFile.path, peerFile.bytes, sourceRevision, oracleRevision)); const binding = native.find(t => t.name === "get_runtime_status" && t.successful && t.runtimeBound && t.output?.activation_ready === true && obj(t.output?.runtime)?.runtime_id === model!.identity.hostRuntimeId && typeof obj(t.output?.runtime)?.working_directory === "string" && createHash("sha256").update(resolve(String(obj(t.output?.runtime)!.working_directory))).digest("hex") === model!.identity.cwdHash); if (!binding) throw new Error("activation-ready runtime/cwd binding absent"); const discovery = { model_to_peer: collectPeerDiscovery(model.identity, peer.identity, native), peer_to_model: collectPeerDiscovery(peer.identity, model.identity, genericTraces) }; const baselineStatus = await waitIdle(model, signal); receipt.baseline = { binding, discovery, turnIds: ids(baseline), status: baselineStatus }; await persist("baseline", receipt.baseline);
      const nonce = `readable-${randomUUID()}`, content = `Information ${nonce}`; const boundary = Date.now(); controllerEvents.push({ kind: "stimulus_boundary", at: boundary }); await persist("controller-boundary", { boundary, controller_events: controllerEvents }); const sent = obj(await peer.call("send_message", { to: model.identity.agent, type: messageType, content, idempotency_key: `${nonce}:message` }, signal)); if (sent?.status !== "sent" || typeof sent.message_id !== "string") throw new Error("generic stimulus send failed"); const messageId = sent.message_id; receipt.plan = { nonce, content, messageType, messageId, boundary }; await persist("stimulus", { plan: receipt.plan, controller_events: controllerEvents });
      const readPrompt = "Call claim_tasks once to read your durable inbox, then end this turn."; controllerEvents.push({ kind: "controller_prompt", at: Date.now(), prompt: readPrompt, purpose: "prompted_readability" }); await persist("read-prompt-started", { controller_events: controllerEvents }); const readAccepted = await model.prompt(readPrompt, signal); const readHistory = await model.history(signal); const readTurnId = assertSetupTurnCompleted(readHistory, readAccepted); if (ids(baseline).includes(readTurnId)) throw new Error("read turn is not new"); await persist("read-prompt-completed", { accepted: readAccepted, turn_id: readTurnId });
      const deadline = Date.now() + 180_000; let proof: Json | undefined, lastError = "";
      while (Date.now() < deadline) { const nativeHistory = await model.history(signal), peerHistory = await peer.history(signal); const nativeFile = await save(join(artifactDir, `native-history-${Date.now()}.json`), sanitizeEvidence(nativeHistory)), peerFileNow = await save(join(artifactDir, `peer-history-${Date.now()}.json`), sanitizeEvidence(peerHistory)); const rows: Json[] = (await observer.xrange(`gptq:inbox-trace:${model.identity.agent}`, "-", "+")).map(([, fields]) => Object.fromEntries(Array.from({ length: fields.length / 2 }, (_, i) => [fields[i * 2]!, fields[i * 2 + 1]!]))); await persist("observation", { native_history_ref: ref(nativeFile.path, nativeFile.bytes, sourceRevision, oracleRevision), peer_history_ref: ref(peerFileNow.path, peerFileNow.bytes, sourceRevision, oracleRevision), raw_trace_rows: rows }); try { const nt = extractNativeTraces(nativeFile.value, model.identity, ref(nativeFile.path, nativeFile.bytes, sourceRevision, oracleRevision)), gt = extractGenericTraces(peerFileNow.value, peer.identity, ref(peerFileNow.path, peerFileNow.bytes, sourceRevision, oracleRevision)); const userTurn = turn(nativeFile.value, readTurnId); if (!userTurn || userTurn.status !== "completed") throw new Error("prompted read turn not completed"); const continuationCalls = (Array.isArray(userTurn.items) ? userTurn.items as unknown[] : []).map(obj).filter(x => x?.type === "mcpToolCall" && typeof x.id === "string").map(x => String(x!.id)); const collected = collectReadableDelivery({ peer: peer.identity, model: model.identity, genericTraces: gt, nativeTraces: nt, postStimulusCallIds: continuationCalls, messageType, content }); if (collected.messageId !== messageId) throw new Error("claim message mismatch"); proof = { collected, prompted_turn_id: readTurnId, read_prompt_acceptance: readAccepted, readability_mode: "explicit_controller_prompt", final_history_ref: ref(nativeFile.path, nativeFile.bytes, sourceRevision, oracleRevision), final_peer_history_ref: ref(peerFileNow.path, peerFileNow.bytes, sourceRevision, oracleRevision), controller_events: controllerEvents }; break; } catch (e) { lastError = String(e); await wait(500); } }
      if (!proof) throw new Error(`readable proof absent: ${lastError}`); receipt.lifecycle = await waitIdle(model, signal); if (controllerEvents.filter(e => e.kind === "controller_prompt" && Number(e.at) >= boundary).length !== 1) throw new Error("expected one explicit readability prompt after stimulus"); receipt.proof = proof; receipt.passed = true; receipt.phase = "completed"; await persist("proof", proof);
    } catch (e) { failure = e; receipt.error = String(e); receipt.phase = "failed"; await persist("failure", String(e)); }
    finally { if (model) await model.history(AbortSignal.timeout(10_000)).then(h => persist("final-model-history", h)).catch(e => { failure ??= e; }); if (peer) await peer.history(AbortSignal.timeout(10_000)).then(h => persist("final-peer-history", h)).catch(e => { failure ??= e; }); for (const [name, action] of [["model", () => model?.close()], ["peer", () => peer?.close()], ["codex", () => codex?.close()], ["generic", () => generic?.close()], ["observer", () => observer?.quit()], ["redis", () => redis?.close()], ["workspace", () => workspace ? rm(workspace, { recursive: true, force: true }) : Promise.resolve()]] as const) { try { await action(); cleanup.push({ name, status: "fulfilled" }); } catch (e) { cleanup.push({ name, status: "rejected", error: String(e) }); failure ??= e; } } receipt.cleanup = cleanup; try { receipt.source_hashes_after = await sourceHashes(); } catch (e) { failure ??= e; } if (JSON.stringify(receipt.source_hashes_before) !== JSON.stringify(receipt.source_hashes_after)) { failure ??= new Error("source hash drift"); receipt.passed = false; } if (cleanup.some(x => x.status === "rejected")) { failure ??= new Error("cleanup failed"); receipt.passed = false; } if (failure) { receipt.passed = false; receipt.phase = "failed"; } receipt.execution = failure ? { status: "failed", detail: String(failure) } : { status: "completed" }; receipt.ended_at = new Date().toISOString(); try { await persist("cleanup", { cleanup, source_hashes_after: receipt.source_hashes_after, execution: receipt.execution }); } catch (e) { receipt.passed = false; failure ??= e; throw failure; } }
    if (failure) throw failure; expect(receipt.passed).toBe(true);
  }, 450_000);
});
